import { createApp } from 'vue'
import App from './App.vue'

import PrimeVue from 'primevue/config'
import Aura from '@primeuix/themes/aura'
import 'primeicons/primeicons.css'
import { definePreset } from '@primeuix/themes'

import ToastService from 'primevue/toastservice'
import ConfirmationService from 'primevue/confirmationservice'
import { createI18n } from 'vue-i18n'
import { dt } from '@primevue/themes'
import '@fortawesome/fontawesome-free/css/fontawesome.css'
import '@fortawesome/fontawesome-free/css/regular.css'
import '@fortawesome/fontawesome-free/css/solid.css'
import '@fortawesome/fontawesome-free/css/brands.css'

import { createWebHistory, createRouter } from 'vue-router'

import { createPinia } from 'pinia'
import auth from '@/services/auth'
import Tooltip from 'primevue/tooltip'
import StyleClass from 'primevue/styleclass'
import Ripple from 'primevue/ripple'
import router from '@/router'

declare module 'vue' {
  interface ComponentCustomProperties {
    $auth: typeof auth
  }
}

const i18n = createI18n({
  legacy: false,
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    en: {
      cashier: 'Cashier',
      kitchen: 'Kitchen',
      admin: 'Admin',
      inventory: 'Inventory',
      product: 'Product | Products',
      order: 'Order | Orders',
      order_items: 'Order Items',
      total: 'Total',
      subtotal: 'Subtotal',
      discount: 'Discount',
      egp: 'EGP',
      search: 'Search',
      signout: 'Signout',
      notifications: 'Notifications',
      clear_all: 'Clear All',
      stashed_orders: 'Stashed Orders',
      chats: 'Chats',
      messages: 'Messages',
      write_message: 'Write Message',
      paylater_orders: 'Paylater Orders',
      checkout: 'Checkout',
      category: 'Category | Categories',
      add_component: 'Add Component',
      name: 'Name',
      quantity: 'Quantity',
      unit: 'Unit',
      status: 'Status',
      actions: 'Actions',
      history: 'History',
      list: 'List',
      report: 'Report | Reports',
      settings: 'Settings',
      language: 'Language | Languages',
      sales: 'Sales',
      validation_required: 'This field is required',
      no_results: 'No results found',
      new_orders_appear: 'New orders will appear here automatically',
      cancel: 'Cancel',
      yes: 'Yes',
      delete: 'Delete',
      save: 'Save',
      retry: 'Retry',
      apply: 'Apply',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      error_occurred: 'An error occurred',
      request_failed: 'Failed to perform the request',
      failed: 'Failed',
      done: 'Done!',
      confirmation: 'Confirmation',
      success: 'Success',
      info: 'Info',
      warn: 'Warning',
      danger: 'Danger',
      id: 'Id',
      key: 'Key',
      value: 'Value',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      comment: 'Comment',
      username: 'Username',
      password: 'Password',
      confirm_password: 'Confirm Password',
      customer: 'Customer',
      about_nutrix:
        'Nutrix is an open-source restaurant management system that provides a comprehensive solution for managing your restaurant operations.',
      version_info: 'version / commit hash :',
      paid: 'PAID',
      unpaid: 'UNPAID',
      pending: 'PENDING',
      cancelled: 'CANCELLED',
      in_progress: 'INPROGRESS',
      finished: 'FINISHED',
      stashed: 'STASHED',
      refunded: 'REFUNDED',
      normal: 'NORMAL',
      csv: 'csv',
      has_refunds: 'has refunds',
      profile: 'Profile',
      access_denied: 'Access denied',
      relogin: 'Relogin',
      welcome_back: 'Welcome Back',
      sign_in_subtitle: 'Sign in to continue to NutrixPOS',
      enter_username: 'Enter your username',
      enter_password: 'Enter your password',
      sign_in: 'Sign In',
      or: 'or',
      no_account: "Don't have an account?",
      contact_admin: 'Contact admin',
      username_required: 'Username is required',
      password_required: 'Password is required',
      invalid_credentials: 'Invalid username or password',
      login_failed: 'Login failed. Please try again.',
      welcome_to_nutrix: 'Welcome to NutrixPOS',
      no_db_configured: 'No database connection has been configured yet.',
      provide_db_details: 'Please provide your MongoDB connection details below.',
      host: 'Host',
      host_placeholder: 'e.g. localhost',
      port: 'Port',
      port_placeholder: 'e.g. 27017',
      database_name: 'Database name',
      database_placeholder: 'e.g. nutrix',
      username_placeholder: 'e.g. webadmin',
      password_placeholder: 'Your database user password',
      confirm_password_placeholder: 'Enter your password again',
      config_saved_restart:
        'Configuration saved! The server is setup — please restart the application to apply the new settings.',
      connection_successful: 'Connection successful! You can now save the configuration.',
      test_connection: 'Test Connection',
      save_and_continue: 'Save & Continue',
      lets_go: "Let's go",
      host_required: 'Host is required',
      port_invalid: 'A valid port number is required',
      database_required: 'Database name is required',
      passwords_no_match: 'Passwords do not match',
      db_connection_failed: 'Failed to connect to database. Check the credentials.',
      config_save_failed: 'Failed to save configuration. Check the backend logs.',
      create_admin_user: 'Create Admin User',
      no_admin_exists: 'No admin user exists yet.',
      create_admin_subtitle: 'Create your administrator account to get started.',
      admin_placeholder: 'e.g. admin',
      email_placeholder: 'e.g. admin@example.com',
      admin_created_success: 'Admin created successfully! Redirecting to home...',
      create_admin: 'Create Admin',
      email_required: 'Email is required',
      email_invalid: 'Invalid email format',
      password_min_length: 'Password must be at least 6 characters',
      admin_create_failed: 'Failed to create admin user',
      delivery_info: 'Delivery info',
      delivery: 'Delivery',
      anonymous: 'Anonymous',
      drafts: 'Drafts',
      main_details: 'Main details',
      insufficient_availability: 'Insufficient availability',
      only_x_left: 'has only {count} left',
      failed_remove_stashed_order: 'Failed to remove stashed order from db',
      failed_load_stashed_orders: 'Failed to get stashed orders',
      order_stashed_success: 'Order stashed successfully!',
      order_stashed_detail: 'Successfully stashed order!',
      error_stashing_item: 'Error Stashing Item',
      order_finished: 'Order Finished',
      failed_save_shop_mode: 'Failed to save shop mode',
      failed_load_material_entries: 'Failed to load material entries',
      order_with_id: 'order with id',
      order_ready_to_serve: 'order is ready to be served!',
      order_in_progress: 'Order in progress!',
      drag_drop_upload: 'Drag and drop files here to upload.',
      enable_fixed_cost: 'Enable Fixed Cost',
      fixed_cost: 'Fixed Cost',
      ready_invalid: 'Ready is not a valid number.',
      price_invalid: 'Price is not a valid number.',
      product_deleted_success: 'Product deleted successfully',
      product_delete_failed: 'Failed to delete product',
      confirm_delete_product: 'Are you sure you want to delete this product?',
      product_updated: 'Product Updated',
      product_added: 'Product Added',
      products_load_failed: 'Failed to load products',
      confirm_delete_material: 'Are you sure you want to delete this material?',
      material_deleted_success: 'Material deleted successfully',
      material_delete_failed: 'Failed to delete material',
      material_edited_success: 'Successfully edited material data',
      material_settings_saved: 'Material settings saved',
      confirm_delete_entry: 'Are you sure you want to delete this entry?',
      entry_deleted: 'Entry deleted!',
      entry_saved: 'Entry saved successfully!',
      component_saved: 'Component saved successfully!',
      category_added_success: 'Category added successfully',
      category_add_failed: 'Failed to add category',
      category_deleted_success: 'Category deleted successfully',
      category_delete_failed: 'Failed to delete category',
      category_updated_success: 'Category updated successfully',
      category_update_failed: 'Failed to update category',
      confirm_delete_category: 'Are you sure you want to delete this category?',
      categories_load_failed: 'Failed to fetch categories',
      order_cancelled_success: 'Order cancelled successfully',
      order_cancel_failed: 'Failed to cancel order',
      confirm_cancel_order: 'Are you sure you want to cancel this order?',
      users_load_failed: 'Failed to load users',
      user_added: 'User Added',
      user_deleted_success: 'User deleted successfully',
      user_delete_failed: 'Failed to delete user',
      confirm_delete_user: 'Are you sure you want to delete this user?',
      enter_new_password: 'Please enter a new password',
      password_changed_success: 'Password changed successfully',
      password_change_failed: 'Failed to change password',
      customer_deleted_success: 'Customer deleted successfully',
      customer_delete_failed: 'Failed to delete customer',
      confirm_delete_customer: 'Are you sure you want to delete this customer?',
      customer_updated: 'Customer Updated',
      customer_added: 'Customer Added',
      customers_load_failed: 'Failed to load customers',
      shop_mode: 'Shop Mode',
      shop_mode_description:
        'Controls which features are available. Restart the app after changing.',
      retail: 'Retail',
      settings_updated: 'Settings updated successfully!',
      settings_update_failed: 'Error updating settings!',
      settings_load_failed: 'Failed to load settings. Please try again.',
      language_load_error: 'Error loading language',
      languages_load_failed: 'Failed to load languages',
      hubsync: 'Hubsync',
      server_host: 'Server Host',
      token: 'Token',
      sync_interval: 'Sync Interval (seconds)',
      buffer_size: 'Buffer Size',
      data_saved_success: 'Data saved successfully',
      select_language: 'Select a Language',
      fill_all_fields: 'Please fill all fields',
      add_with_comment: 'Add with comment',
      product_details: 'Product details',
      confirm_finish_order: 'Are you sure you want to finish the order?',
      order_finished_detail: 'Good job!',
      finish_order_failed: 'Failed finishing order!',
      custom_data: 'Custom data',
      edit_custom_data: 'Edit custom data',
      add_custom_data: 'Add custom data',
      tip_added: 'Tip added',
      tip_removed: 'Tip removed',
      confirm_delete_custom_data: 'Are you sure you want to delete this custom data entry?',
      custom_data_updated: 'Custom data updated',
      money_collected: 'Money collected',
      print_signal_sent: 'Print signal sent',
      items: 'Item(s)',
      return: 'return',
      returning_item: 'Returning',
      money_to_refund: 'Money To refund',
      destination: 'Destination:',
      dispose: 'Dispose',
      waste: 'Waste',
      custom_materials_products: 'Custom (materials / products)',
      materials: 'Materials',
      item_refunded: 'Item refunded',
      refund_error: 'Refund failed',
      order_paid_success: 'Successfully paid order {id}',
      about_nutrix_short: 'Nutrix is an open-source restaurant management system',
      select_option: 'Select option',
      insufficient_availability_summary: 'Insufficient availability',
      only_x_left_detail: '{name} has only {count} left',
      order_submitted_success: 'Order in progress!',
      continue_with_mode: 'Continue with {mode} mode',
      select_mode_continue: 'Select a mode to continue',
      edit: 'Edit',
      remove: 'Remove',
      add: 'Add',
      choose: 'Choose',
      finish: 'Finish',
      star: 'Star',
      current: 'Current',
      drawer: 'Drawer',
      stash_order: 'Stash order',
      do_you_confirm: 'Do you confirm',
      cancel_order: 'Cancel order',
      edit_password: 'Edit Password',
      show_entries: 'Show entries',
      refund: 'Refund',
      loading: 'Loading',
      logs: 'Logs',
      returning: 'Returning',
      draft_order_tooltip: 'Draft order for later interactions',
      auto_finish_tooltip: 'Auto finish order and consume components from inventory',
      exact_cost_tooltip:
        'Exact cost of materials will be used for each product during order creation chosen from specific material entry',
      average_cost_tooltip:
        'Average cost of materials available in the inventory will be used for each product during order creation, material/s with earliest expiration will be consumed first',
      for_more_support: 'For more support & collaboration visit',
      instock: 'IN STOCK',
      lowstock: 'LOW STOCK',
      export_csv: 'Export CSV',
      image: 'Image',
      fiscal: 'Fiscal',
      fiscal_description: 'FURS ZAPOS fiscal receipt configuration',
      fiscal_enabled: 'Enable fiscalization',
      fiscal_environment: 'Environment',
      fiscal_tax_number: 'Tax number',
      fiscal_business_premise_id: 'Business premise ID',
      fiscal_electronic_device_id: 'Electronic device ID',
      fiscal_software_supplier_tn: 'Software supplier tax number',
      fiscal_certificate_path: 'Certificate path (.p12)',
      fiscal_certificate_password: 'Certificate password',
      fiscal_invoice_number: 'Next invoice number',
      fiscal_test_connection: 'Test connection',
      fiscal_connection_success: 'FURS connection successful',
      fiscal_connection_failed: 'FURS connection failed',
      fiscalize: 'Fiscalize',
      fiscalized: 'Fiscalized',
      fiscalization_failed: 'Fiscalization failed',
      fiscalization_not_configured:
        'No fiscal module enabled. Configure FURS or Croatian fiscalization in Settings.',
      fiscal_receipt: 'Fiscal receipt',
      eor: 'EOR (Unique Invoice ID)',
      offline_pending: 'Pending fiscalization (offline)',
      fiscal_hr: 'Croatian fiscalization (Fina eRačun)',
      fiscal_hr_description: 'Croatian CIS fiscalization settings — TR-2006 format',
      fiscal_hr_enabled: 'Enable Croatian fiscalization',
      fiscal_hr_oib: 'OIB (Tax number)',
      fiscal_hr_business_premise_id: 'Business premise ID (OznPosPr)',
      fiscal_hr_electronic_device_id: 'Electronic device ID (OznNapUr)',
      fiscal_hr_certificate_path: 'Certificate path (.p12)',
      fiscal_hr_certificate_password: 'Certificate password',
      fiscal_hr_invoice_number: 'Next invoice number',
      fiscal_hr_environment: 'Environment',
      fiscal_hr_test_connection: 'Test CIS connection',
      fiscal_hr_connection_success: 'CIS connection successful',
      fiscal_hr_connection_failed: 'CIS connection failed',
      fiscal_hr_operator_oib: 'Operator OIB',
      jir: 'JIR (Unique Receipt ID)',
      label_test: 'Test',
      label_production: 'Production',
      tables: 'Tables',
      tables_description: 'Manage restaurant tables',
      table_number: 'Table Number',
      table_name: 'Table Name',
      table_capacity: 'Capacity',
      table_zone: 'Zone',
      table_status: 'Status',
      add_table: 'Add Table',
      indoor: 'Indoor',
      outdoor: 'Outdoor',
      bar: 'Bar',
      vip: 'VIP',
      available: 'Available',
      occupied: 'Occupied',
      reserved: 'Reserved',
      cleaning: 'Cleaning',
      qr_code: 'QR Code',
      generate_qr: 'Generate QR',
      scan_qr: 'Scan QR',
      qr_code_generated: 'QR code generated successfully',
      qr_generate_failed: 'Failed to generate QR code',
      table_added_success: 'Table added successfully',
      table_add_failed: 'Failed to add table',
      table_updated_success: 'Table updated successfully',
      table_update_failed: 'Failed to update table',
      table_deleted_success: 'Table deleted successfully',
      table_delete_failed: 'Failed to delete table',
      tables_load_failed: 'Failed to load tables',
      confirm_delete_table: 'Are you sure you want to delete this table?',
      ai_search: 'AI Search',
      ai_search_description: 'Use AI to find products quickly',
      ai_voice: 'Voice Search',
      ai_suggestions: 'AI-powered product suggestions',
      voice_ordering: 'Voice Ordering',
      voice_ordering_description: 'Speak to search and add items to your order',
      smart_suggestions: 'Smart Suggestions',
      search_results: 'Search Results',
      search_failed: 'Search failed',
      no_results: 'No results found',
      add_to_order: 'Add to Order',
      added_to_order: 'added to order',
      start_recording: 'Start Recording',
      stop_recording: 'Stop Recording',
      score: 'Score',
      transcription: 'Transcription',
      voice_recognition_failed: 'Voice recognition failed',
      voice_search_failed: 'Voice search failed',
      microphone_access_denied: 'Microphone access denied',
      install_app: 'Install Nutrix POS',
      install_description: 'Add to your home screen for quick access',
      install: 'Install',
      dismiss: 'Dismiss',
      offline_mode: 'Offline mode',
      branches: 'Branches',
      branch_name: 'Branch Name',
      branch_address: 'Address',
      branch_phone: 'Phone',
      branch_email: 'Email',
      add_branch: 'Add Branch',
      edit_branch: 'Edit Branch',
      branch_added: 'Branch added successfully',
      branch_updated: 'Branch updated successfully',
      branch_deleted: 'Branch deleted successfully',
      split_bill: 'Split Bill',
      split_bill_details: 'Split Bill Details',
      split_type: 'Split Type',
      split_count: 'Number of Parts',
      equal: 'Equal',
      custom: 'Custom',
      by_item: 'By Item',
      part: 'Part',
      parts: 'Parts',
      pay: 'Pay',
      pay_split_part: 'Pay Split Part',
      select_part: 'Select Part',
      payment_method: 'Payment Method',
      cash: 'Cash',
      card: 'Card',
      voucher: 'Voucher',
      mobile_pay: 'Mobile Pay',
      create_split_bill: 'Create Split Bill',
      split_bill_created: 'Split bill created successfully',
      payment_recorded: 'Payment recorded successfully',
      order_id: 'Order ID',
      amount: 'Amount',
      active: 'Active',
      inactive: 'Inactive',
      create: 'Create',
      view: 'View',
      employee_scheduling: 'Employee Scheduling',
      scheduling: 'Scheduling',
      add_shift: 'Add Shift',
      edit_shift: 'Edit Shift',
      shift_added: 'Shift added successfully',
      shift_updated: 'Shift updated successfully',
      shift_deleted: 'Shift deleted successfully',
      employee: 'Employee',
      date: 'Date',
      date_range: 'Date Range',
      start_time: 'Start Time',
      end_time: 'End Time',
      role: 'Role',
      branch: 'Branch',
      reservations: 'Reservations',
      reservation: 'Reservation',
      add_reservation: 'Add Reservation',
      edit_reservation: 'Edit Reservation',
      reservation_added: 'Reservation added successfully',
      reservation_updated: 'Reservation updated successfully',
      reservation_deleted: 'Reservation deleted successfully',
      customer_name: 'Customer Name',
      guests: 'Guests',
      filter_by_date: 'Filter by date',
      time: 'Time',
      promotions: 'Promotions',
      promotion: 'Promotion',
      add_promotion: 'Add Promotion',
      edit_promotion: 'Edit Promotion',
      promotion_added: 'Promotion added successfully',
      promotion_updated: 'Promotion updated successfully',
      promotion_deleted: 'Promotion deleted successfully',
      code: 'Code',
      min_order: 'Min. Order',
      start_date: 'Start Date',
      end_date: 'End Date',
      usage_limit: 'Usage Limit',
      loyalty_program: 'Loyalty Program',
      loyalty: 'Loyalty',
      points: 'Points',
      tier: 'Tier',
      total_spent: 'Total Spent',
      earn_points: 'Earn Points',
      redeem_points: 'Redeem Points',
      add_points: 'Add Points',
      redeem: 'Redeem',
      points_added: 'Points added successfully',
      points_redeemed: 'Points redeemed successfully',
      transaction_history: 'Transaction History',
      all_tiers: 'All Tiers',
      reports: 'Reports',
      report: 'Report',
      today_revenue: 'Today Revenue',
      today_orders: 'Today Orders',
      average_order: 'Average Order',
      sales_report: 'Sales Report',
      sales_summary: 'Sales Summary',
      total_revenue: 'Total Revenue',
      total_orders: 'Total Orders',
      total_items: 'Total Items',
      net_revenue: 'Net Revenue',
      top_products: 'Top Products',
      product: 'Product',
      revenue: 'Revenue',
      inventory_report: 'Inventory Report',
      inventory_status: 'Inventory Status',
      total_materials: 'Total Materials',
      low_stock: 'Low Stock',
      out_of_stock: 'Out of Stock',
      total_value: 'Total Value',
      low_stock_items: 'Low Stock Items',
      generate: 'Generate',
      refresh: 'Refresh',
      notes: 'Notes',
      multi_location: 'Multi-Location Dashboard',
      location_overview: 'Location Overview',
      total_branches: 'Total Branches',
      consolidated_revenue: 'Consolidated Revenue',
      consolidated_orders: 'Consolidated Orders',
      branch_comparison: 'Branch Comparison',
      branch_name: 'Branch Name',
      today_revenue: 'Today Revenue',
      week_revenue: 'Week Revenue',
      month_revenue: 'Month Revenue',
      active_staff: 'Active Staff',
      tables_occupied: 'Tables Occupied',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      gift_cards: 'Gift Cards',
      gift_card: 'Gift Card',
      create_gift_card: 'Create Gift Card',
      gift_card_code: 'Gift Card Code',
      initial_amount: 'Initial Amount',
      current_amount: 'Current Amount',
      expiry_date: 'Expiry Date',
      redeem_gift_card: 'Redeem Gift Card',
      redeem: 'Redeem',
      issue: 'Issue',
      redeemed: 'Redeemed',
      expired: 'Expired',
      insufficient_balance: 'Insufficient Balance',
      gift_card_created: 'Gift Card Created',
      gift_card_redeemed: 'Gift Card Redeemed',
      transaction_history: 'Transaction History',
      inventory_transfers: 'Inventory Transfers',
      create_transfer: 'Create Transfer',
      from_branch: 'From Branch',
      to_branch: 'To Branch',
      pending: 'Pending',
      completed: 'Completed',
      cancelled: 'Cancelled',
      transfer_created: 'Transfer Created',
      transfer_completed: 'Transfer Completed',
      transfer_cancelled: 'Transfer Cancelled',
      material: 'Material',
      quantity: 'Quantity',
      fiscal_dashboard: 'Fiscal Dashboard',
      fiscal_receipts: 'Fiscal Receipts',
      invoice_number: 'Invoice Number',
      eor: 'EOR',
      zoi: 'ZOI',
      fiscalized: 'Fiscalized',
      total_receipts: 'Total Receipts',
      total_amount: 'Total Amount',
      filter: 'Filter',
      floor_plan: 'Floor Plan',
      total_tables: 'Total Tables',
      available: 'Available',
      occupied: 'Occupied',
      reserved: 'Reserved',
      cleaning: 'Cleaning',
      seats: 'Seats',
      all_zones: 'All Zones',
      transfer_table: 'Transfer Table',
      transfer: 'Transfer',
      merge_tables: 'Merge Tables',
      merge: 'Merge',
      from_table: 'From Table',
      to_table: 'To Table',
      select_table: 'Select Table',
      table_transferred: 'Table Transferred',
      tables_merged: 'Tables Merged',
      status_updated: 'Status Updated',
      employee_tips: 'Employee Tips',
      record_tip: 'Record Tip',
      tip_summary: 'Tip Summary',
      total_tips: 'Total Tips',
      tip_count: 'Tip Count',
      average_tip: 'Average Tip',
      payout: 'Payout',
      payout_tips: 'Payout Tips',
      payout_method: 'Payout Method',
      payout_history: 'Payout History',
      cash: 'Cash',
      card: 'Card',
      tip_recorded: 'Tip Recorded',
      tip_paid_out: 'Tip Paid Out',
      kitchen_stations: 'Kitchen Stations',
      create_station: 'Create Station',
      station_name: 'Station Name',
      station_created: 'Station Created',
      item_status_updated: 'Item Status Updated',
      preparing: 'Preparing',
      ready: 'Ready',
      pending: 'Pending',
      done: 'Done',
      notifications: 'Notifications',
      mark_all_read: 'Mark All as Read',
      no_notifications: 'No Notifications',
      unread: 'Unread',
      mark_read: 'Mark as Read',
      email: 'Email',
      notes: 'Notes',
      tags: 'Tags',
      loyalty_points: 'Loyalty Points',
      total_spent: 'Total Spent',
      order_count: 'Order Count',
      last_order_date: 'Last Order',
      preferences: 'Preferences',
      order_history: 'Order History',
      customer_details: 'Customer Details',
      no_orders: 'No Orders Found',
      customer_stats: 'Customer Statistics',
      no_tags: 'No Tags',
      filter_by_tag: 'Filter by Tag',
      all_customers: 'All Customers',
      vip_customers: 'VIP Customers',
      accounting_export: 'Accounting Export',
      quickbooks_description: 'Export sales data for QuickBooks accounting software.',
      xero_description: 'Export sales data for Xero accounting software.',
      export_quickbooks: 'Export for QuickBooks',
      export_xero: 'Export for Xero',
      export_started: 'Export started. File will download shortly.',
      menu_engineering: 'Menu Engineering',
      analyze: 'Analyze',
      total_items: 'Total Items',
      avg_profit: 'Avg Profit',
      profitability_matrix: 'Profitability Matrix',
      stars: 'Stars',
      plowhorses: 'Plowhorses',
      puzzles: 'Puzzles',
      dogs: 'Dogs',
      stars_description: 'High profit, high popularity',
      plowhorses_description: 'Low profit, high popularity',
      puzzles_description: 'High profit, low popularity',
      dogs_description: 'Low profit, low popularity',
      sold: 'Sold',
      profit_per_item: 'Profit/Item',
      margin: 'Margin',
      select_date_range: 'Select a date range to analyze menu performance',
      analysis_failed: 'Failed to load analysis',
      no_data: 'No data available',
      employee_performance: 'Employee Performance',
      total_employees: 'Total Employees',
      avg_sales_per_hour: 'Avg Sales/Hour',
      leaderboard: 'Leaderboard',
      employee: 'Employee',
      total_sales: 'Total Sales',
      orders: 'Orders',
      avg_order: 'Avg Order',
      sales_per_hour: 'Sales/Hour',
      tips: 'Tips',
      rank: 'Rank',
      top_products_per_employee: 'Top Products per Employee',
      qty: 'Qty',
      revenue: 'Revenue',
      performance_load_failed: 'Failed to load performance data',
      suppliers: 'Suppliers',
      add_supplier: 'Add Supplier',
      edit_supplier: 'Edit Supplier',
      contact_name: 'Contact Name',
      website: 'Website',
      active: 'Active',
      inactive: 'Inactive',
      no_suppliers: 'No suppliers found',
      supplier_saved: 'Supplier saved successfully',
      supplier_deleted: 'Supplier deleted successfully',
      supplier_orders: 'Supplier Orders',
      save_failed: 'Failed to save supplier',
      delete_failed: 'Failed to delete supplier',
      expense_tracking: 'Expense Tracking',
      add_expense: 'Add Expense',
      edit_expense: 'Edit Expense',
      total_expenses: 'Total Expenses',
      monthly_total: 'Monthly Total',
      by_category: 'By Category',
      category: 'Category',
      count: 'Count',
      recent_expenses: 'Recent Expenses',
      no_expenses: 'No expenses found',
      expense_saved: 'Expense saved successfully',
      select_category: 'Select Category',
      time_clock: 'Time Clock',
      clock_in_out: 'Clock In/Out',
      clock_in: 'Clock In',
      clock_out: 'Clock Out',
      clock_in_time: 'Clock In Time',
      currently_clocked_in: 'Currently Clocked In',
      no_active_shifts: 'No active shifts',
      today_summary: 'Today Summary',
      total_hours: 'Total Hours',
      shifts: 'Shifts',
      avg_per_shift: 'Avg/Shift',
      overtime: 'Overtime',
      clocked_in: 'Clocked in successfully',
      clocked_out: 'Clocked out successfully',
      clock_in_failed: 'Failed to clock in',
      clock_out_failed: 'Failed to clock out',
      select_employee: 'Select an employee',
      warning: 'Warning',
      waste_tracking: 'Waste Tracking',
      add_waste_entry: 'Add Waste Entry',
      waste_entries: 'Waste Entries',
      no_waste_entries: 'No waste entries found',
      waste_entry_saved: 'Waste entry saved successfully',
      waste_entry_deleted: 'Waste entry deleted successfully',
      total_waste_cost: 'Total Waste Cost',
      total_entries: 'Total Entries',
      by_reason: 'By Reason',
      by_material: 'By Material',
      reason: 'Reason',
      cost: 'Cost',
      material_name: 'Material Name',
      material_id: 'Material ID',
      recorded_by: 'Recorded By',
      select_reason: 'Select Reason',
      online_orders: 'Online Orders',
      order_online: 'Order Online',
      no_online_orders: 'No online orders yet',
      order_type: 'Order Type',
      order_status_updated: 'Order status updated',
      update_failed: 'Failed to update',
      all_statuses: 'All Statuses',
      confirm: 'Confirm',
      preparing: 'Preparing',
      ready: 'Ready',
      delivered: 'Delivered',
      your_cart: 'Your Cart',
      cart_empty: 'Your cart is empty',
      item: 'Item',
      place_order: 'Place Order',
      order_placed: 'Order placed successfully!',
      order_failed: 'Failed to place order',
      delivery_address: 'Delivery Address',
      fill_required_fields: 'Please fill in your name and phone number',
      menu_load_failed: 'Failed to load menu',
      no_products_available: 'No products available',
      all: 'All',
      cart: 'Cart',
      staff_chat: 'Staff Chat',
      channels: 'Channels',
      new_channel: 'New Channel',
      channel_name: 'Channel Name',
      no_messages: 'No messages yet',
      type_message: 'Type a message...',
      send_failed: 'Failed to send message',
      channel_created: 'Channel created successfully',
      create_failed: 'Failed to create channel',
      audit_log: 'Audit Log',
      audit_entries: 'Audit Entries',
      no_audit_entries: 'No audit entries found',
      all_actions: 'All Actions',
      all_resources: 'All Resources',
      by_action: 'By Action',
      by_resource: 'By Resource',
      by_user: 'By User',
      action: 'Action',
      resource: 'Resource',
      resource_id: 'Resource ID',
      user: 'User',
      ip_address: 'IP Address',
      timestamp: 'Timestamp',
      receipt_customization: 'Receipt Customization',
      receipt_templates: 'Receipt Templates',
      add_template: 'Add Template',
      no_templates: 'No templates',
      template_created: 'Template created',
      template_saved: 'Template saved',
      template_deleted: 'Template deleted',
      template_editor: 'Template Editor',
      receipt_preview: 'Receipt Preview',
      business_name: 'Business Name',
      business_address: 'Business Address',
      business_phone: 'Business Phone',
      business_tax_id: 'Business Tax ID',
      paper_width: 'Paper Width',
      header: 'Header',
      footer: 'Footer',
      show_logo: 'Show Logo',
      show_tax_id: 'Show Tax ID',
      show_qr_code: 'Show QR Code',
      show_server: 'Show Server',
      show_table: 'Show Table',
      save_template: 'Save Template',
      preview: 'Preview',
      print_settings: 'Print Settings',
      printer_name: 'Printer Name',
      printer_ip: 'Printer IP',
      print_copies: 'Print Copies',
      auto_print: 'Auto Print',
      save_settings: 'Save Settings',
      default: 'Default',
      inventory_alerts: 'Inventory Alerts',
      add_rule: 'Add Rule',
      save_rule: 'Save Rule',
      rule_saved: 'Alert rule saved',
      rule_deleted: 'Alert rule deleted',
      alert_rules: 'Alert Rules',
      recent_alerts: 'Recent Alerts',
      no_rules: 'No alert rules',
      no_alerts: 'No alerts',
      low_threshold: 'Low Threshold',
      critical_threshold: 'Critical Threshold',
      current: 'Current',
      read: 'Read',
      severity: 'Severity',
      critical: 'Critical',
      active_rules: 'Active Rules',
      unread_alerts: 'Unread Alerts',
       add_alert_rule: 'Add Alert Rule',
       multi_payment: 'Multi-Payment',
       payment_summary: 'Payment Summary',
       grand_total: 'Grand Total',
       mobile_pay: 'Mobile Pay',
       gift_cards: 'Gift Cards',
       daily_breakdown: 'Daily Breakdown',
       no_payments: 'No payments recorded',
       transactions: 'Transactions',
       customer_display: 'Customer Display',
       add_display: 'Add Display',
       display_configs: 'Display Configurations',
       no_displays: 'No display configurations',
       display_name: 'Display Name',
       slide_interval: 'Slide Interval',
       show_promotions: 'Show Promotions',
       show_menu: 'Show Menu',
       show_order_status: 'Show Order Status',
       show_wait_time: 'Show Wait Time',
       welcome_message: 'Welcome Message',
       edit_display: 'Edit Display',
       delete_display_confirm: 'Are you sure you want to delete this display?',
       preview: 'Preview',
       current_orders: 'Current Orders',
       our_menu: 'Our Menu',
       tableside_ordering: 'Tableside Ordering',
       add_table: 'Add Table',
       table_sessions: 'Table Sessions',
       no_sessions: 'No table sessions',
       table: 'Table',
       table_label: 'Table Label',
       guests: 'Guests',
       zone: 'Zone',
       opened: 'Opened',
       closed: 'Closed',
       qr_code: 'QR Code',
       view_orders: 'View Orders',
       table_menu: 'Table Menu',
       place_order: 'Place Order',
       order_placed: 'Order Placed',
       staff_training: 'Staff Training',
       training_in_progress: 'Training in Progress',
       complete_step: 'Complete Step',
       finish_training: 'Finish Training',
       training_completed: 'Training Completed!',
       retake: 'Retake',
       start: 'Start',
       steps: 'steps',
       customer_feedback: 'Customer Feedback',
       avg_rating: 'Average Rating',
       total_reviews: 'Total Reviews',
       food_rating: 'Food Rating',
       service_rating: 'Service Rating',
       no_feedback: 'No feedback yet',
       respond_to_feedback: 'Respond to Feedback',
       your_response: 'Your Response',
       comment: 'Comment',
       anonymous: 'Anonymous',
       responded: 'Responded',
       all_reviews: 'All Reviews',
        order_placed_message: 'Your order has been placed and is being prepared!',
        menu_placeholder: 'Browse our delicious menu!',
        dashboard: 'Dashboard',
        admin_dashboard: 'Admin Dashboard',
        today_sales: "Today's Sales",
        yesterday: 'Yesterday',
        active_orders: 'Active Orders',
        pending_orders: 'Pending Orders',
        low_stock_alerts: 'Low Stock Alerts',
        recent_feedback: 'Recent Feedback',
        quick_actions: 'Quick Actions',
        views: 'Views',
        comparison: 'Comparison',
        sales_today: 'Sales Today',
        orders_today: 'Orders Today',
        loading_data: 'Loading data...',
      },
   },
 })

const Noir = definePreset(Aura, {
  components: {
    progressspinner: {
      colorScheme: {
        light: {
          root: {
            colorOne: '{primary.900}',
            colorTwo: '{primary.900}',
            colorThree: '{primary.900}',
            colorFour: '{primary.900}',
          },
        },
        dark: {
          root: {
            colorOne: '{primary.900}',
            colorTwo: '{primary.900}',
            colorThree: '{primary.900}',
            colorFour: '{primary.900}',
          },
        },
      },
    },
  },
  semantic: {
    primary: {
      50: '{zinc.50}',
      100: '{zinc.100}',
      200: '{zinc.200}',
      300: '{zinc.300}',
      400: '{zinc.400}',
      500: '{zinc.500}',
      600: '{zinc.600}',
      700: '{zinc.700}',
      800: '{zinc.800}',
      900: '{zinc.900}',
      950: '{zinc.950}',
    },
    colorScheme: {
      light: {
        primary: {
          color: '#14977B',
          inverseColor: '#a5c22f',
          hoverColor: '#14977B',
          activeColor: '#14977B',
        },
        highlight: {
          background: '#DEDB69',
          focusBackground: '#DEDB69',
          color: '#173350',
          focusColor: '#173350',
        },
      },
      dark: {
        primary: {
          color: '#a5c22f',
          inverseColor: '#14977B',
          hoverColor: '#a5c22f',
          activeColor: '#a5c22f',
        },
        highlight: {
          background: '#fff6c7',
          focusBackground: '#FFDC00',
          color: '#173350',
          focusColor: '#173350',
        },
      },
    },
  },
})

const app = createApp(App).use(createPinia())
app.config.globalProperties.$auth = auth

app
  .use(router)
  .use(PrimeVue, {
    theme: {
      preset: Noir,
      options: {
        prefix: 'p',
        darkModeSelector: '.my-app-dark',
        cssLayer: false,
      },
    },
  })
  .use(ToastService)
  .use(ConfirmationService)
  .use(i18n)
  .directive('tooltip', Tooltip)
  .directive('styleclass', StyleClass)
  .directive('ripple', Ripple)
  .mount('#app')
